### ISSUE TITLE
Unit Tests for voting results

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-dao#8]
We created those text examples:

we need to 
- [x] write them as table
- [x] implement them as unit test
- [x] add unit tests the cover the "almost" cases, like 33,332 %, to ensure there are no inaccuracies. 

Participation: 320000 DMD (let’s consider 1 million tokens to be 100%) = 32% (33% required is required for Open proposal type)
Positive answers: 246400 DMD (77% from the whole participation)
Negative answers: 73600 DMD (23% from the whole participation)
77%-23% = 54% exceeding Yes (33% required for Open proposal type)
Result: the community agrees with the decision, but due to the low participation it is not accepted.Participation: 500000 DMD (let’s consider 1 million tokens to be 100%) = 50% (33% required is required for Open proposal type)
Positive answers: 300000 DMD (60% from the whole participation)
Negative answers: 200000 DMD (40% from the whole participation)
60%-40% = 20% exceeding Yes (33% required for Open proposal type)
Result: the majority of the community agrees with the decision, the participation is rather high, but due to the low difference between Yes and No answers it is not accepted.Participation: 600000 DMD (let’s consider 1 million tokens to be 100%) = 60% (33% required is required for Open proposal type)
Positive answers: 402000 DMD (67% from the whole participation)
Negative answers: 198000 DMD (33% from the whole participation)
67%-33% = 34% exceeding Yes (33% required for Open proposal type)
Result: the majority of the community agrees with the decision, the participation is high, the difference between Yes and No answers is in the defined range so the proposal is accepted.Participation: 100000 DMD (let’s consider 1 million tokens to be 100%) = 10% (33% required is required for Open proposal type)
Positive answers: 50000 DMD (50% from the whole participation)
Negative answers: 50000 DMD (50% from the whole participation)
50%-50% = 0% exceeding Yes (33% required for Open proposal type)
Result: the community answers split 50/50, the participation is very low, the difference between Yes and No answers is out of the defined range so the proposal is not accepted.

**Comment by MSalman6** [comment]
@SurfingNerd completed in https://github.com/MSalman6/diamond-contracts-dao/commit/a7dc9c3371a47a82b2c1ab9e7a73704b9aada202
